In [1]:
import numpy as np

## Array creation techniques (functions)

In [ ]:
list = [1,2,5,6,8] # 1d array
np.array(list)

array([1, 2, 5, 6, 8])

In [7]:
np.zeros((2,3),dtype=int) # 2D array

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
np.full((2,4),fill_value=6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random data generation

In [15]:
np.random.rand(3,2)

array([[0.15701012, 0.63047737],
       [0.09643798, 0.54881321],
       [0.46963633, 0.56774122]])

In [19]:
np.random.randn(3,3)

array([[ 1.70382384e+00, -1.52232231e+00, -7.49937534e-01],
       [ 1.19762984e+00,  1.44109557e+00,  1.09823428e+00],
       [-3.11389221e-04,  3.48551304e-02, -1.99456462e+00]])

In [25]:
np.random.randint(10,15,(3,3))

array([[12, 10, 13],
       [12, 10, 12],
       [14, 10, 11]], dtype=int32)

## range function

In [31]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.linspace(10,26)

array([10.        , 10.32653061, 10.65306122, 10.97959184, 11.30612245,
       11.63265306, 11.95918367, 12.28571429, 12.6122449 , 12.93877551,
       13.26530612, 13.59183673, 13.91836735, 14.24489796, 14.57142857,
       14.89795918, 15.2244898 , 15.55102041, 15.87755102, 16.20408163,
       16.53061224, 16.85714286, 17.18367347, 17.51020408, 17.83673469,
       18.16326531, 18.48979592, 18.81632653, 19.14285714, 19.46938776,
       19.79591837, 20.12244898, 20.44897959, 20.7755102 , 21.10204082,
       21.42857143, 21.75510204, 22.08163265, 22.40816327, 22.73469388,
       23.06122449, 23.3877551 , 23.71428571, 24.04081633, 24.36734694,
       24.69387755, 25.02040816, 25.34693878, 25.67346939, 26.        ])

In [37]:
arr = np.random.randint(10,15,(3,3))

In [40]:
arr

array([[11, 10, 10],
       [14, 10, 10],
       [10, 12, 10]], dtype=int32)

In [38]:
arr.ndim

2

In [39]:
arr.shape

(3, 3)

In [41]:
arr.size

9

In [42]:
arr.dtype

dtype('int32')

In [43]:
arr.nbytes

36

In [44]:
arr.itemsize

4

In [46]:
arr = np.array([1,2,3,5,6,8])

In [47]:
arr.dtype

dtype('int64')

In [52]:
arr_float = arr.astype(float)
arr_float .dtype

dtype('float64')

In [54]:
float_readings = np.random.uniform(20,30,size=10)
float_readings

array([26.16777933, 26.91320018, 28.8646523 , 21.42604174, 20.27811685,
       25.00612408, 25.85131957, 25.19339083, 23.36472706, 20.15079012])

In [55]:
float_readings.nbytes

80

In [58]:
int_reading =float_readings.astype(np.int32)
int_reading.nbytes

40