## NumPy Array Indexing, Slicing & Subsetting 

In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])


## indexing

In [ ]:
# 1D indexing
print(arr[0])
print(arr[-2])


10
40


In [7]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 2D indexing
print(arr2d[1,1])
print(arr2d[2,1])

5
8


## Slicing

In [12]:
arr =np.array([10,20,30,40,50])

In [ ]:
# 1D slicing
arr1 = arr[1:4]
print(arr1)

[20 30 40]


In [15]:
print(arr[:4])

[10 20 30 40]


In [16]:
print(arr[2:])

[30 40 50]


In [18]:
print(arr[::3])

[10 40]


In [22]:
#2D slicing
arr2d = np.random.randint(10,20,(3,3))
arr2d

array([[11, 11, 17],
       [11, 14, 14],
       [19, 16, 14]], dtype=int32)

In [23]:
print(arr2d[0:2,1:3])

[[11 17]
 [14 14]]


## boolean indexing

In [24]:
data = np.array([12,14,28,16,8,30])
# filter values > 12
filtered = data[data>12]

print(filtered)


[14 28 16 30]


## fancy indexing

In [25]:
data1 = np.array([12,14,28,16,8,30])
indexes = [0,2,4]
print(data1[indexes])

[12 28  8]


## views Vs copies

In [26]:
data2 = np.array([12,14,28,16,8,30])
view = data2[1:4]
print(data2)
print(view)

[12 14 28 16  8 30]
[14 28 16]


In [27]:
view[1]=35

In [29]:
print(data2)

[12 14 35 16  8 30]


In [32]:
copy = data[[1,2,3,4]]
print(copy)

[14 28 16  8]


In [33]:
copy[1] =45

In [34]:
print(copy)
print(data2)

[14 45 16  8]
[12 14 35 16  8 30]
