In [1]:
import numpy as np

In [ ]:
# Reshaping
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
reshaped = arr.reshape(2,-1)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [25]:
# resizing
arr1 = np.array([1,2,3])
resize = np.resize(arr1,(3,4))
print(resize)


[[1 2 3 1]
 [2 3 1 2]
 [3 1 2 3]]


In [34]:
# flattening
print(resize)
arr2 = resize.flatten()
print(arr2)

[[1 2 3 1]
 [2 3 1 2]
 [3 1 2 3]]
[1 2 3 1 2 3 1 2 3 1 2 3]


In [36]:
# ravel 
ravel = resize.ravel()
print(ravel)

[1 2 3 1 2 3 1 2 3 1 2 3]


In [37]:
ravel[0] = 125

In [38]:
print(resize)
print(ravel)

[[125   2   3   1]
 [  2   3   1   2]
 [  3   1   2   3]]
[125   2   3   1   2   3   1   2   3   1   2   3]


In [39]:
print(resize)
arr2[10]=480 #flattened resize
print(arr2)



[[125   2   3   1]
 [  2   3   1   2]
 [  3   1   2   3]]
[  1   2   3   1   2   3   1   2   3   1 480   3]


In [40]:
# transposing
arr3 = np.array([[1,2,3],[4,5,6]])
transpose = arr3.T
print(arr3)
print(transpose)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
