## Indexing & Slicing in NumPy 

In [1]:
import numpy as np

In [3]:
data = np.array([100,200,300,400,500,600])

In [ ]:
# indexing
print(data[0]) #positive indexing
print(data[-1])# negitive indexing

100
600


In [9]:
data1 = np.array([[100,200,300],[400,500,600]])
print(data1)

[[100 200 300]
 [400 500 600]]


In [11]:
print(data1[0,1])
print(data1[0][1])

200
200


In [12]:
#slicing 
data2 = np.array([100,200,300,400,500,600])

In [14]:
print(data2[1:6:2])

[200 400 600]


In [16]:
data3 = np.array([[100,200,300],[400,500,600]])
print(data3)

[[100 200 300]
 [400 500 600]]


In [19]:
# 2d array slicing
print(data3[0:2,1:3])

[[200 300]
 [500 600]]
