In [1]:
import numpy as np


In [3]:
arr = np.array([10,15,20,25,30,35])
mask =arr>20
print(mask)
print(arr[mask])

[False False False  True  True  True]
[25 30 35]


In [4]:
arr1 =np.array([[10,20,30],[40,50,60],[70,80,90]])
mask1 = arr1>45
print(arr1[arr1>45])

[50 60 70 80 90]


In [ ]:
# & (and) ,| (or) , ~ (not)
arr2 = np.array([10,20,30,40,50,-999])
print(arr2[(arr2>20)&(arr2<50)])
print(arr2[~(arr2 % 20 ==0)])

[30 40]
[10 30 50]
