In [1]:
import numpy as np


In [15]:
arr1 = np.array([10,20,30,40,50])
index_values = [1,4,4,2]
print(arr1[index_values])
arr1[[1,2]] = [-1,-1]
print(arr1)

[20 50 50 30]
[10 -1 -1 40 50]


In [ ]:
arr2 =np.array([[10,20,30],[40,50,60],[70,80,90]])
row = [1,2,1]
col = [2,1,2]
print(arr2[row,col])    
print(arr2)

[60 80 60]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
